// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Title field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Email Block field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email_block
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  email_block: prismic.RichTextField;

  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Footer links field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Brand Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.brand_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  brand_logo: prismic.ImageField<never>;

  /**
   * Nav Links field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.nav_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Nav CTA field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.nav_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | ReportSliceSlice
  | VideoShowcaseSlice
  | MarqueeSlice
  | EventsSlice
  | VideoWithBigTitleSlice
  | AboutSectionSlice
  | ImageCarouselSlice
  | HeroSectionSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | AgendaSlice
  | SpeakersOfBangaloreEditionSlice
  | ParticipantsSlice
  | OldHeroSectionSlice
  | VideoShowcaseSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | HomePageDocument
  | PageDocument;

/**
 * Item in *AboutSection → Default → Primary → Overview Cards*
 */
export interface AboutSectionSliceDefaultPrimaryOverviewCardsItem {
  /**
   * Icon field in *AboutSection → Default → Primary → Overview Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.overview_cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *AboutSection → Default → Primary → Overview Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.overview_cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *AboutSection → Default → Primary → Overview Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.overview_cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Intro Text field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.intro_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro_text: prismic.RichTextField;

  /**
   * Overview Cards field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.overview_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  overview_cards: prismic.GroupField<
    Simplify<AboutSectionSliceDefaultPrimaryOverviewCardsItem>
  >;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Item in *Agenda → Default → Primary → Blocks*
 */
export interface AgendaSliceDefaultPrimaryBlocksItem {
  /**
   * Time field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Title field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Title or Images field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].title_or_images
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_or_images: prismic.RichTextField;

  /**
   * Short description field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Speaker One field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker: prismic.ImageField<never>;

  /**
   * Speaker One Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  speaker_name: prismic.KeyTextField;

  /**
   * LinkedInOne field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].linkedinone
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedinone: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Speaker Two field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_two
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_two: prismic.ImageField<never>;

  /**
   * Speaker Two Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_two_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  speaker_two_name: prismic.KeyTextField;

  /**
   * LinkedInTwo field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].linkedintwo
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedintwo: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Speaker Three Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_three_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_three_image: prismic.ImageField<never>;

  /**
   * Speaker Three Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_three_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  speaker_three_name: prismic.RichTextField;

  /**
   * Speaker Three LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_three_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  speaker_three_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Speaker Four Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_four_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_four_image: prismic.ImageField<never>;

  /**
   * Speaker Four Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_four_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  speaker_four_name: prismic.RichTextField;

  /**
   * Speaker Four LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_four_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  speaker_four_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Speaker Five Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_five_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_five_image: prismic.ImageField<never>;

  /**
   * Speaker Five Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_five_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  speaker_five_name: prismic.RichTextField;

  /**
   * Speaker Five LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_five_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  speaker_five_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Moderator One Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_one_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  moderator_one_image: prismic.ImageField<never>;

  /**
   * Moderator One Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_one_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  moderator_one_name: prismic.RichTextField;

  /**
   * Moderator One LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_one_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  moderator_one_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Moderator Two Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_two_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  moderator_two_image: prismic.ImageField<never>;

  /**
   * Moderator Two Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_two_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  moderator_two_name: prismic.RichTextField;

  /**
   * Moderator Two LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_two_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  moderator_two_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Moderator Three Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_three_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  moderator_three_image: prismic.ImageField<never>;

  /**
   * Moderator Three Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_three_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  moderator_three_name: prismic.RichTextField;

  /**
   * Moderator Three LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_three_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  moderator_three_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Moderator Four Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_four_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  moderator_four_image: prismic.ImageField<never>;

  /**
   * Moderator Four Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_four_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  moderator_four_name: prismic.RichTextField;

  /**
   * Moderator Four LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_four_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  moderator_four_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Facilitator One Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_one_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  facilitator_one_image: prismic.ImageField<never>;

  /**
   * Facilitator One Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_one_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  facilitator_one_name: prismic.RichTextField;

  /**
   * Facilitator One LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_one_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  facilitator_one_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Facilitator Two Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_two_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  facilitator_two_image: prismic.ImageField<never>;

  /**
   * Facilitator Two Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_two_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  facilitator_two_name: prismic.RichTextField;

  /**
   * Facilitator Two LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_two_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  facilitator_two_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Facilitator Three Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_three_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  facilitator_three_image: prismic.ImageField<never>;

  /**
   * Facilitator Three Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_three_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  facilitator_three_name: prismic.RichTextField;

  /**
   * Facilitator Three LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_three_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  facilitator_three_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Facilitator Four Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_four_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  facilitator_four_image: prismic.ImageField<never>;

  /**
   * Facilitator Four Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_four_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  facilitator_four_name: prismic.RichTextField;

  /**
   * Facilitator Four LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_four_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  facilitator_four_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Agenda → Default → Primary*
 */
export interface AgendaSliceDefaultPrimary {
  /**
   * Show Slice field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: agenda.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Heading field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Blocks field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blocks: prismic.GroupField<Simplify<AgendaSliceDefaultPrimaryBlocksItem>>;
}

/**
 * Default variation for Agenda Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AgendaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AgendaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Agenda*
 */
type AgendaSliceVariation = AgendaSliceDefault;

/**
 * Agenda Shared Slice
 *
 * - **API ID**: `agenda`
 * - **Description**: Agenda
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AgendaSlice = prismic.SharedSlice<"agenda", AgendaSliceVariation>;

/**
 * Item in *Events → Default → Primary → Events*
 */
export interface EventsSliceDefaultPrimaryEventsItem {
  /**
   * Icon field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Location field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].location
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  location: prismic.RichTextField;

  /**
   * Title field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Date Text field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].date_text
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date_text: prismic.DateField;

  /**
   * Date field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].date
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  date: prismic.RichTextField;

  /**
   * CTA Button field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Events → Default → Primary*
 */
export interface EventsSliceDefaultPrimary {
  /**
   * Main Heading field in *Events → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * UpcomingEventsHeading field in *Events → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.upcomingeventsheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  upcomingeventsheading: prismic.RichTextField;

  /**
   * PastEventsHeading field in *Events → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.pasteventsheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  pasteventsheading: prismic.RichTextField;

  /**
   * Events field in *Events → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  events: prismic.GroupField<Simplify<EventsSliceDefaultPrimaryEventsItem>>;
}

/**
 * Default variation for Events Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Events*
 */
type EventsSliceVariation = EventsSliceDefault;

/**
 * Events Shared Slice
 *
 * - **API ID**: `events`
 * - **Description**: Events
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventsSlice = prismic.SharedSlice<"events", EventsSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *ImageCarousel → Default → Primary → Carousel Image*
 */
export interface ImageCarouselSliceDefaultPrimaryCarouselImageItem {
  /**
   * Image field in *ImageCarousel → Default → Primary → Carousel Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_carousel.default.primary.carousel_image[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ImageCarousel → Default → Primary*
 */
export interface ImageCarouselSliceDefaultPrimary {
  /**
   * Carousel Image field in *ImageCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_carousel.default.primary.carousel_image[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousel_image: prismic.GroupField<
    Simplify<ImageCarouselSliceDefaultPrimaryCarouselImageItem>
  >;
}

/**
 * Default variation for ImageCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageCarousel*
 */
type ImageCarouselSliceVariation = ImageCarouselSliceDefault;

/**
 * ImageCarousel Shared Slice
 *
 * - **API ID**: `image_carousel`
 * - **Description**: ImageCarousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCarouselSlice = prismic.SharedSlice<
  "image_carousel",
  ImageCarouselSliceVariation
>;

/**
 * Item in *Marquee → Default → Primary → Marquee*
 */
export interface MarqueeSliceDefaultPrimaryMarqueeItem {
  /**
   * Logo field in *Marquee → Default → Primary → Marquee*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.marquee[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Marquee → Default → Primary*
 */
export interface MarqueeSliceDefaultPrimary {
  /**
   * Heading field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Marquee field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.marquee[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  marquee: prismic.GroupField<Simplify<MarqueeSliceDefaultPrimaryMarqueeItem>>;
}

/**
 * Default variation for Marquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Marquee*
 */
type MarqueeSliceVariation = MarqueeSliceDefault;

/**
 * Marquee Shared Slice
 *
 * - **API ID**: `marquee`
 * - **Description**: Marquee
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueeSlice = prismic.SharedSlice<
  "marquee",
  MarqueeSliceVariation
>;

/**
 * Primary content in *OldHeroSection → Default → Primary*
 */
export interface OldHeroSectionSliceDefaultPrimary {
  /**
   * Heading field in *OldHeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *OldHeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Date text field in *OldHeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_hero_section.default.primary.date_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_text: prismic.KeyTextField;

  /**
   * Date field in *OldHeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: old_hero_section.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  date: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Time field in *OldHeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: old_hero_section.default.primary.time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Location field in *OldHeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: old_hero_section.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  location: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image or Video field in *OldHeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: old_hero_section.default.primary.image_or_video
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_or_video: prismic.ImageField<never>;

  /**
   * Video Toggle field in *OldHeroSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: old_hero_section.default.primary.video_toggle
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  video_toggle: prismic.BooleanField;

  /**
   * CTA Link field in *OldHeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: old_hero_section.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for OldHeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OldHeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OldHeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OldHeroSection*
 */
type OldHeroSectionSliceVariation = OldHeroSectionSliceDefault;

/**
 * OldHeroSection Shared Slice
 *
 * - **API ID**: `old_hero_section`
 * - **Description**: OldHeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OldHeroSectionSlice = prismic.SharedSlice<
  "old_hero_section",
  OldHeroSectionSliceVariation
>;

/**
 * Item in *Participants → Default → Primary → Companies*
 */
export interface ParticipantsSliceDefaultPrimaryCompaniesItem {
  /**
   * Logo field in *Participants → Default → Primary → Companies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: participants.default.primary.companies[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link field in *Participants → Default → Primary → Companies*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: participants.default.primary.companies[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Participants → Default → Primary*
 */
export interface ParticipantsSliceDefaultPrimary {
  /**
   * Show Slice field in *Participants → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: participants.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Companies field in *Participants → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: participants.default.primary.companies[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  companies: prismic.GroupField<
    Simplify<ParticipantsSliceDefaultPrimaryCompaniesItem>
  >;
}

/**
 * Default variation for Participants Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ParticipantsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ParticipantsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Participants*
 */
type ParticipantsSliceVariation = ParticipantsSliceDefault;

/**
 * Participants Shared Slice
 *
 * - **API ID**: `participants`
 * - **Description**: Participants
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ParticipantsSlice = prismic.SharedSlice<
  "participants",
  ParticipantsSliceVariation
>;

/**
 * Primary content in *ReportSlice → Default → Primary*
 */
export interface ReportSliceSliceDefaultPrimary {
  /**
   * Asset field in *ReportSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: report_slice.default.primary.asset
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  asset: prismic.ImageField<never>;

  /**
   * Heading field in *ReportSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: report_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ReportSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: report_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Subscription info field in *ReportSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: report_slice.default.primary.subscription_info
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subscription_info: prismic.RichTextField;
}

/**
 * Default variation for ReportSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReportSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReportSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ReportSlice*
 */
type ReportSliceSliceVariation = ReportSliceSliceDefault;

/**
 * ReportSlice Shared Slice
 *
 * - **API ID**: `report_slice`
 * - **Description**: ReportSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReportSliceSlice = prismic.SharedSlice<
  "report_slice",
  ReportSliceSliceVariation
>;

/**
 * Item in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
 */
export interface SpeakersOfBangaloreEditionSliceDefaultPrimarySpeakerItem {
  /**
   * Speaker Image field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].speaker_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_image: prismic.ImageField<never>;

  /**
   * Name field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].name_rich
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name_rich: prismic.RichTextField;

  /**
   * Role field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].role_rich
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  role_rich: prismic.RichTextField;

  /**
   * LinkedIn field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *SpeakersOfBangaloreEdition → secondaryVar → Primary → Speaker*
 */
export interface SpeakersOfBangaloreEditionSliceSecondaryVarPrimarySpeakerItem {
  /**
   * Speaker Image field in *SpeakersOfBangaloreEdition → secondaryVar → Primary → Speaker*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.speaker[].speaker_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_image: prismic.ImageField<never>;

  /**
   * Name field in *SpeakersOfBangaloreEdition → secondaryVar → Primary → Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.speaker[].name_rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name_rich_text: prismic.RichTextField;

  /**
   * Role field in *SpeakersOfBangaloreEdition → secondaryVar → Primary → Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.speaker[].role_rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  role_rich_text: prismic.RichTextField;

  /**
   * LinkedIn field in *SpeakersOfBangaloreEdition → secondaryVar → Primary → Speaker*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.speaker[].linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *SpeakersOfBangaloreEdition → Default → Primary*
 */
export interface SpeakersOfBangaloreEditionSliceDefaultPrimary {
  /**
   * Heading field in *SpeakersOfBangaloreEdition → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Speaker field in *SpeakersOfBangaloreEdition → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  speaker: prismic.GroupField<
    Simplify<SpeakersOfBangaloreEditionSliceDefaultPrimarySpeakerItem>
  >;
}

/**
 * Default variation for SpeakersOfBangaloreEdition Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpeakersOfBangaloreEditionSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<SpeakersOfBangaloreEditionSliceDefaultPrimary>,
    never
  >;

/**
 * Primary content in *SpeakersOfBangaloreEdition → secondaryVar → Primary*
 */
export interface SpeakersOfBangaloreEditionSliceSecondaryVarPrimary {
  /**
   * Show Slice field in *SpeakersOfBangaloreEdition → secondaryVar → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Heading field in *SpeakersOfBangaloreEdition → secondaryVar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Speaker field in *SpeakersOfBangaloreEdition → secondaryVar → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.speaker[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  speaker: prismic.GroupField<
    Simplify<SpeakersOfBangaloreEditionSliceSecondaryVarPrimarySpeakerItem>
  >;
}

/**
 * secondaryVar variation for SpeakersOfBangaloreEdition Slice
 *
 * - **API ID**: `secondaryVar`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpeakersOfBangaloreEditionSliceSecondaryVar =
  prismic.SharedSliceVariation<
    "secondaryVar",
    Simplify<SpeakersOfBangaloreEditionSliceSecondaryVarPrimary>,
    never
  >;

/**
 * Slice variation for *SpeakersOfBangaloreEdition*
 */
type SpeakersOfBangaloreEditionSliceVariation =
  | SpeakersOfBangaloreEditionSliceDefault
  | SpeakersOfBangaloreEditionSliceSecondaryVar;

/**
 * SpeakersOfBangaloreEdition Shared Slice
 *
 * - **API ID**: `speakers_of_bangalore_edition`
 * - **Description**: SpeakersOfBangaloreEdition
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpeakersOfBangaloreEditionSlice = prismic.SharedSlice<
  "speakers_of_bangalore_edition",
  SpeakersOfBangaloreEditionSliceVariation
>;

/**
 * Item in *VideoShowcase → Default → Primary → VideoBlocks*
 */
export interface VideoShowcaseSliceDefaultPrimaryVideoblocksItem {
  /**
   * Thumbnail Image field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].thumbnail_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail_image: prismic.ImageField<never>;

  /**
   * Thumbnail Logo field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].thumbnail_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail_logo: prismic.ImageField<never>;

  /**
   * Video Link field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].video_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Name of person field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].name_of_person
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name_of_person: prismic.RichTextField;

  /**
   * Role of person, Company field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].role_of_person_company
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  role_of_person_company: prismic.RichTextField;

  /**
   * Company Logo field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].company_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  company_logo: prismic.ImageField<never>;
}

/**
 * Primary content in *VideoShowcase → Default → Primary*
 */
export interface VideoShowcaseSliceDefaultPrimary {
  /**
   * Heading field in *VideoShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *VideoShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * VideoBlocks field in *VideoShowcase → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  videoblocks: prismic.GroupField<
    Simplify<VideoShowcaseSliceDefaultPrimaryVideoblocksItem>
  >;
}

/**
 * Default variation for VideoShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoShowcase*
 */
type VideoShowcaseSliceVariation = VideoShowcaseSliceDefault;

/**
 * VideoShowcase Shared Slice
 *
 * - **API ID**: `video_showcase`
 * - **Description**: VideoShowcase
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoShowcaseSlice = prismic.SharedSlice<
  "video_showcase",
  VideoShowcaseSliceVariation
>;

/**
 * Primary content in *VideoWithBigTitle → Default → Primary*
 */
export interface VideoWithBigTitleSliceDefaultPrimary {
  /**
   * Heading field in *VideoWithBigTitle → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_with_big_title.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Video Link field in *VideoWithBigTitle → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video_with_big_title.default.primary.video_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Preview Video field in *VideoWithBigTitle → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: video_with_big_title.default.primary.preview_video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  preview_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Short description field in *VideoWithBigTitle → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_with_big_title.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;
}

/**
 * Default variation for VideoWithBigTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoWithBigTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoWithBigTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoWithBigTitle*
 */
type VideoWithBigTitleSliceVariation = VideoWithBigTitleSliceDefault;

/**
 * VideoWithBigTitle Shared Slice
 *
 * - **API ID**: `video_with_big_title`
 * - **Description**: VideoWithBigTitle
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoWithBigTitleSlice = prismic.SharedSlice<
  "video_with_big_title",
  VideoWithBigTitleSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimaryOverviewCardsItem,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      AgendaSlice,
      AgendaSliceDefaultPrimaryBlocksItem,
      AgendaSliceDefaultPrimary,
      AgendaSliceVariation,
      AgendaSliceDefault,
      EventsSlice,
      EventsSliceDefaultPrimaryEventsItem,
      EventsSliceDefaultPrimary,
      EventsSliceVariation,
      EventsSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ImageCarouselSlice,
      ImageCarouselSliceDefaultPrimaryCarouselImageItem,
      ImageCarouselSliceDefaultPrimary,
      ImageCarouselSliceVariation,
      ImageCarouselSliceDefault,
      MarqueeSlice,
      MarqueeSliceDefaultPrimaryMarqueeItem,
      MarqueeSliceDefaultPrimary,
      MarqueeSliceVariation,
      MarqueeSliceDefault,
      OldHeroSectionSlice,
      OldHeroSectionSliceDefaultPrimary,
      OldHeroSectionSliceVariation,
      OldHeroSectionSliceDefault,
      ParticipantsSlice,
      ParticipantsSliceDefaultPrimaryCompaniesItem,
      ParticipantsSliceDefaultPrimary,
      ParticipantsSliceVariation,
      ParticipantsSliceDefault,
      ReportSliceSlice,
      ReportSliceSliceDefaultPrimary,
      ReportSliceSliceVariation,
      ReportSliceSliceDefault,
      SpeakersOfBangaloreEditionSlice,
      SpeakersOfBangaloreEditionSliceDefaultPrimarySpeakerItem,
      SpeakersOfBangaloreEditionSliceDefaultPrimary,
      SpeakersOfBangaloreEditionSliceSecondaryVarPrimarySpeakerItem,
      SpeakersOfBangaloreEditionSliceSecondaryVarPrimary,
      SpeakersOfBangaloreEditionSliceVariation,
      SpeakersOfBangaloreEditionSliceDefault,
      SpeakersOfBangaloreEditionSliceSecondaryVar,
      VideoShowcaseSlice,
      VideoShowcaseSliceDefaultPrimaryVideoblocksItem,
      VideoShowcaseSliceDefaultPrimary,
      VideoShowcaseSliceVariation,
      VideoShowcaseSliceDefault,
      VideoWithBigTitleSlice,
      VideoWithBigTitleSliceDefaultPrimary,
      VideoWithBigTitleSliceVariation,
      VideoWithBigTitleSliceDefault,
    };
  }
}
