// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Title field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Email Block field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email_block
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  email_block: prismic.RichTextField;

  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Footer links field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Brand Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.brand_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  brand_logo: prismic.ImageField<never>;

  /**
   * Nav Links field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.nav_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Nav CTA field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.nav_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | ReportSliceSlice
  | VideoShowcaseSlice
  | MarqueeSlice
  | EventsSlice
  | VideoWithBigTitleSlice
  | AboutSectionSlice
  | ImageCarouselSlice
  | HeroSectionSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | HomePageDocument;

/**
 * Item in *AboutSection → Default → Primary → Overview Cards*
 */
export interface AboutSectionSliceDefaultPrimaryOverviewCardsItem {
  /**
   * Icon field in *AboutSection → Default → Primary → Overview Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.overview_cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *AboutSection → Default → Primary → Overview Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.overview_cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *AboutSection → Default → Primary → Overview Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.overview_cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Intro Text field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.intro_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro_text: prismic.RichTextField;

  /**
   * Overview Cards field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.overview_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  overview_cards: prismic.GroupField<
    Simplify<AboutSectionSliceDefaultPrimaryOverviewCardsItem>
  >;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Item in *Events → Default → Primary → Events*
 */
export interface EventsSliceDefaultPrimaryEventsItem {
  /**
   * Icon field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Location field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].location
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  location: prismic.RichTextField;

  /**
   * Title field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Date Text field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].date_text
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date_text: prismic.DateField;

  /**
   * Date field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].date
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  date: prismic.RichTextField;

  /**
   * CTA Button field in *Events → Default → Primary → Events*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[].cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Events → Default → Primary*
 */
export interface EventsSliceDefaultPrimary {
  /**
   * Main Heading field in *Events → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_heading: prismic.RichTextField;

  /**
   * UpcomingEventsHeading field in *Events → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.upcomingeventsheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  upcomingeventsheading: prismic.RichTextField;

  /**
   * PastEventsHeading field in *Events → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.pasteventsheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  pasteventsheading: prismic.RichTextField;

  /**
   * Events field in *Events → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.events[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  events: prismic.GroupField<Simplify<EventsSliceDefaultPrimaryEventsItem>>;
}

/**
 * Default variation for Events Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Events*
 */
type EventsSliceVariation = EventsSliceDefault;

/**
 * Events Shared Slice
 *
 * - **API ID**: `events`
 * - **Description**: Events
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventsSlice = prismic.SharedSlice<"events", EventsSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *ImageCarousel → Default → Primary → Carousel Image*
 */
export interface ImageCarouselSliceDefaultPrimaryCarouselImageItem {
  /**
   * Image field in *ImageCarousel → Default → Primary → Carousel Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_carousel.default.primary.carousel_image[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ImageCarousel → Default → Primary*
 */
export interface ImageCarouselSliceDefaultPrimary {
  /**
   * Carousel Image field in *ImageCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_carousel.default.primary.carousel_image[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousel_image: prismic.GroupField<
    Simplify<ImageCarouselSliceDefaultPrimaryCarouselImageItem>
  >;
}

/**
 * Default variation for ImageCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageCarousel*
 */
type ImageCarouselSliceVariation = ImageCarouselSliceDefault;

/**
 * ImageCarousel Shared Slice
 *
 * - **API ID**: `image_carousel`
 * - **Description**: ImageCarousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageCarouselSlice = prismic.SharedSlice<
  "image_carousel",
  ImageCarouselSliceVariation
>;

/**
 * Item in *Marquee → Default → Primary → Marquee*
 */
export interface MarqueeSliceDefaultPrimaryMarqueeItem {
  /**
   * Logo field in *Marquee → Default → Primary → Marquee*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.marquee[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Marquee → Default → Primary*
 */
export interface MarqueeSliceDefaultPrimary {
  /**
   * Heading field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Marquee field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.marquee[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  marquee: prismic.GroupField<Simplify<MarqueeSliceDefaultPrimaryMarqueeItem>>;
}

/**
 * Default variation for Marquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Marquee*
 */
type MarqueeSliceVariation = MarqueeSliceDefault;

/**
 * Marquee Shared Slice
 *
 * - **API ID**: `marquee`
 * - **Description**: Marquee
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueeSlice = prismic.SharedSlice<
  "marquee",
  MarqueeSliceVariation
>;

/**
 * Primary content in *ReportSlice → Default → Primary*
 */
export interface ReportSliceSliceDefaultPrimary {
  /**
   * Asset field in *ReportSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: report_slice.default.primary.asset
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  asset: prismic.ImageField<never>;

  /**
   * Heading field in *ReportSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: report_slice.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ReportSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: report_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Subscription info field in *ReportSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: report_slice.default.primary.subscription_info
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subscription_info: prismic.RichTextField;
}

/**
 * Default variation for ReportSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReportSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReportSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ReportSlice*
 */
type ReportSliceSliceVariation = ReportSliceSliceDefault;

/**
 * ReportSlice Shared Slice
 *
 * - **API ID**: `report_slice`
 * - **Description**: ReportSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReportSliceSlice = prismic.SharedSlice<
  "report_slice",
  ReportSliceSliceVariation
>;

/**
 * Item in *VideoShowcase → Default → Primary → VideoBlocks*
 */
export interface VideoShowcaseSliceDefaultPrimaryVideoblocksItem {
  /**
   * Thumbnail Image field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].thumbnail_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail_image: prismic.ImageField<never>;

  /**
   * Thumbnail Logo field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].thumbnail_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail_logo: prismic.ImageField<never>;

  /**
   * Video Link field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].video_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Name of person field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].name_of_person
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name_of_person: prismic.RichTextField;

  /**
   * Role of person, Company field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].role_of_person_company
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  role_of_person_company: prismic.RichTextField;

  /**
   * Company Logo field in *VideoShowcase → Default → Primary → VideoBlocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[].company_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  company_logo: prismic.ImageField<never>;
}

/**
 * Primary content in *VideoShowcase → Default → Primary*
 */
export interface VideoShowcaseSliceDefaultPrimary {
  /**
   * Heading field in *VideoShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *VideoShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * VideoBlocks field in *VideoShowcase → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: video_showcase.default.primary.videoblocks[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  videoblocks: prismic.GroupField<
    Simplify<VideoShowcaseSliceDefaultPrimaryVideoblocksItem>
  >;
}

/**
 * Default variation for VideoShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoShowcase*
 */
type VideoShowcaseSliceVariation = VideoShowcaseSliceDefault;

/**
 * VideoShowcase Shared Slice
 *
 * - **API ID**: `video_showcase`
 * - **Description**: VideoShowcase
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoShowcaseSlice = prismic.SharedSlice<
  "video_showcase",
  VideoShowcaseSliceVariation
>;

/**
 * Primary content in *VideoWithBigTitle → Default → Primary*
 */
export interface VideoWithBigTitleSliceDefaultPrimary {
  /**
   * Heading field in *VideoWithBigTitle → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_with_big_title.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Video Link field in *VideoWithBigTitle → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video_with_big_title.default.primary.video_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Preview Video field in *VideoWithBigTitle → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: video_with_big_title.default.primary.preview_video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  preview_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Short description field in *VideoWithBigTitle → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_with_big_title.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;
}

/**
 * Default variation for VideoWithBigTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoWithBigTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoWithBigTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoWithBigTitle*
 */
type VideoWithBigTitleSliceVariation = VideoWithBigTitleSliceDefault;

/**
 * VideoWithBigTitle Shared Slice
 *
 * - **API ID**: `video_with_big_title`
 * - **Description**: VideoWithBigTitle
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoWithBigTitleSlice = prismic.SharedSlice<
  "video_with_big_title",
  VideoWithBigTitleSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimaryOverviewCardsItem,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      EventsSlice,
      EventsSliceDefaultPrimaryEventsItem,
      EventsSliceDefaultPrimary,
      EventsSliceVariation,
      EventsSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ImageCarouselSlice,
      ImageCarouselSliceDefaultPrimaryCarouselImageItem,
      ImageCarouselSliceDefaultPrimary,
      ImageCarouselSliceVariation,
      ImageCarouselSliceDefault,
      MarqueeSlice,
      MarqueeSliceDefaultPrimaryMarqueeItem,
      MarqueeSliceDefaultPrimary,
      MarqueeSliceVariation,
      MarqueeSliceDefault,
      ReportSliceSlice,
      ReportSliceSliceDefaultPrimary,
      ReportSliceSliceVariation,
      ReportSliceSliceDefault,
      VideoShowcaseSlice,
      VideoShowcaseSliceDefaultPrimaryVideoblocksItem,
      VideoShowcaseSliceDefaultPrimary,
      VideoShowcaseSliceVariation,
      VideoShowcaseSliceDefault,
      VideoWithBigTitleSlice,
      VideoWithBigTitleSliceDefaultPrimary,
      VideoWithBigTitleSliceVariation,
      VideoWithBigTitleSliceDefault,
    };
  }
}
