// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  events: dynamic(() => import("./Events")),
  hero_section: dynamic(() => import("./Hero")),
  image_carousel: dynamic(() => import("./ImageCarousel")),
  marquee: dynamic(() => import("./Marquee")),
  report_slice: dynamic(() => import("./ReportSlice")),
  video_showcase: dynamic(() => import("./VideoShowcase")),
  video_with_big_title: dynamic(() => import("./VideoWithBigTitle")),
};
