// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  agenda: dynamic(() => import("./Agenda")),
  events: dynamic(() => import("./Events")),
  hero_section: dynamic(() => import("./HeroSection")),
  image_carousel: dynamic(() => import("./ImageCarousel")),
  marquee: dynamic(() => import("./LogoMarquee")),
  old_hero_section: dynamic(() => import("./HeroSectionTwoColumnLayout")),
  participants: dynamic(() => import("./Participants")),
  report_slice: dynamic(() => import("./GetReport")),
  speakers_of_bangalore_edition: dynamic(() => import("./Speakers")),
  video_showcase: dynamic(() => import("./VideoShowcase")),
  video_with_big_title: dynamic(() => import("./HeadingAndVideo")),
};
